project_id = "ktjchmgzawcfmmjzzpmq"

[functions.processDailyEntry]
verify_jwt = false

[functions.deleteAccount]
verify_jwt = false

[functions.exportMyData]
verify_jwt = false

[functions.search-articles]
verify_jwt = false

[functions.mindfulness-exercises]
verify_jwt = false